pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn /var/lib/jenkins/workspace/pipeline/my-app/javaapp/pom.xml clean install'
      }
    }
  }
}
