pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'your-credentials-id',
                    url: 'https://github.com/your-repo-url.git'
            }
        }

        stage('Debug Workspace') {
            steps {
                script {
                    sh '''
                    echo "Workspace contents:"
                    ls -l
                    '''
                }
            }
        }

        stage('Build Docker') {
            steps {
                script {
                    sh '''
                    echo "Building Docker Image"
                    docker build -t sheshdhar3-cicd-e2e:${BUILD_NUMBER} .
                    '''
                }
            }
        }
    }
}


