pipeline {
    agent { dockerfile true }
    stages {
        stage('Test') {
            steps {
                sh 'node --version'
                sh 'git --version'
                sh 'curl --version'
            }
        }
    }
}