pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
	// compile java code
        sh 'javac hello_world.java'
      }
      steps {
        // run java application
        sh 'java hello_world.java'
      }	
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
	// run node app
        sh 'node hello.js'
      }
    }
  }
}
