pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    // Print Hello, World!
                    echo 'Hello, World!'
                }
            }
        }
    }
}

