pipeline {
    agent {
        docker {
            image 'abhishekf5/maven-abhishek-docker-agent:v1'
            args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Build') {
            steps {
                    script {
                        dir('java-maven-sonar-argocd-helm-k8s/spring-boot-app') {
                        sh "mvn clean install"
                        }
                    }
            }
        }
        stage('Build and Push Docker Image') {
              environment {
                DOCKER_IMAGE = "abyvarghese1990/ultimate-cicd-new:${BUILD_NUMBER}"
                REGISTRY_CREDENTIALS = credentials('dockerhub')
              }
              steps {
                script {
                    sh 'cd java-maven-sonar-argocd-helm-k8s/spring-boot-app && docker build -t ${DOCKER_IMAGE} .'
                    def dockerImage = docker.image("${DOCKER_IMAGE}")
                    docker.withRegistry('https://index.docker.io/v1/', "dockerhub") {
                        dockerImage.push()
                    }
                }
              }
    }
    }
}
