pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
    
    stage('echo') {
      steps {
        sh 'echo "bruce"'
        sh 'touch k.txt'
        cat k.txt
      }
    }
  
   stage('echo') {
      steps {
        sh 'echo "bruce"'
        sh 'touch k.txt'
        cat k.txt
      }
    }
  }
}
