pipeline {
    agent any
    
    stages {
        stage('Build and Run Node.js') {
            steps {
                script {
                    // Node.js
                    // Run Node.js application in a Docker container
                    docker.image('node:latest').inside('-u root') {
                        // Assuming nodejs directory contains the Node.js application files
                        dir('nodejs') {
                            // Checkout Node.js code from repository
                            checkout scm
                            
                            // Install dependencies
                            sh 'npm install'
                            
                            // Run the Node.js application
                            sh 'node app.js'
                        }
                    }
                }
            }
        }
        
        stage('Build and Run Python') {
            steps {
                script {
                    // Python
                    // Run Python script in a Docker container
                    docker.image('python:latest').inside('-u root') {
                        // Assuming python directory contains the Python application files
                        dir('python') {
                            // Checkout Python code from repository
                            checkout scm
                            
                            // Run the Python script
                            sh 'python hello_world.py'
                        }
                    }
                }
            }
        }
    }
}

